apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2022-01-17T16:27:46Z","generation":2,"labels":{"app":"hello-world-rest"},"name":"hello-world-rest","namespace":"default","resourceVersion":"719790","uid":"7b8044df-3709-4865-a876-f2f49ca4c505"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"hello-world-rest"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"hello-world-rest"}},"spec":{"containers":[{"image":"devarshi1981/hello-world-rest-api:0.0.4-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"hello-world-rest-api","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2022-01-17T16:27:46Z","lastUpdateTime":"2022-01-17T16:27:50Z","message":"ReplicaSet \"hello-world-rest-785d79d8c9\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2022-01-17T16:40:27Z","lastUpdateTime":"2022-01-17T16:40:27Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":2,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
  creationTimestamp: "2022-01-17T16:27:46Z"
  generation: 3
  labels:
    app: hello-world-rest
  name: hello-world-rest
  namespace: default
  resourceVersion: "721236"
  uid: 7b8044df-3709-4865-a876-f2f49ca4c505
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world-rest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-rest
    spec:
      containers:
      - image: devarshi1981/hello-world-rest-api:0.0.4-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: hello-world-rest-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-01-17T16:27:46Z"
    lastUpdateTime: "2022-01-17T16:27:50Z"
    message: ReplicaSet "hello-world-rest-785d79d8c9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-17T16:44:15Z"
    lastUpdateTime: "2022-01-17T16:44:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
