apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-01-17T16:38:39Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest
  name: hello-world-rest
  namespace: default
  resourceVersion: "719360"
  uid: 4028eb53-d78f-43eb-816b-0eae3cc1d465
spec:
  clusterIP: 10.112.10.75
  clusterIPs:
  - 10.112.10.75
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32105
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.69.118.174
